import matplotlib.pyplot as plt  
import numpy as np
plt.figure(1)
plt.figure(2)
plt.figure(1)
xData = np.arange(0, 10, 1)
yData1 = xData.__pow__(2.0)
yData2 = np.arange(15, 61, 5)
plt.figure(num=1, figsize=(8, 6))
plt.title('Plot 1', size=14)
plt.xlabel('x-axis', size=14)
plt.ylabel('y-axis', size=14)
plt.plot(xData, yData1, color='b', linestyle='--', marker='o', label='y1 data')
plt.plot(xData, yData2, color='r', linestyle='-', label='y2 data')

plt.figure(2)
x = np.linspace(-4, 4, 200) 
f1 = np.power(10, x) 
f2 = np.power(np.e, x) 
f3 = np.power(2, x)  

plt.plot(x, f1,'rs',x,f2,'b+',x,f3,'gD',linewidth=2) 
plt.axis([-4, 4, -0.5, 8])
plt.text(0.7, 7.5, r'$10^x$', size=16)
plt.text(1.8, 7.5, r'$e^x$',size=16)
plt.text(2.8, 7.5, r'$2^x$',size=16)
plt.legend(('slat1','slat2','expriment'),loc=2)
plt.title('A simple example', size=16)
plt.savefig('power.png', dpi=300)
plt.box('off')
plt.show()  
